export const defaultPattern =
  '$$DATEMINUS12$$\\$$IMAGETYPE$$\\$$DATETIME$$_$$FILTER$$_$$SENSORTEMP$$_$$EXPOSURETIME$$s_$$FRAMENR$$';

export const allTokenKeys = [
  '$$FILTER$$',
  '$$DATE$$',
  '$$DATEUTC$$',
  '$$DATEMINUS12$$',
  '$$DATETIME$$',
  '$$TIME$$',
  '$$TIMEUTC$$',
  '$$MJD$$',
  '$$FRAMENR$$',
  '$$IMAGETYPE$$',
  '$$BINNING$$',
  '$$SENSORTEMP$$',
  '$$TEMPERATURESETPOINT$$',
  '$$EXPOSURETIME$$',
  '$$TARGETNAME$$',
  '$$GAIN$$',
  '$$OFFSET$$',
  '$$RMS$$',
  '$$RMSARCSEC$$',
  '$$PEAKRA$$',
  '$$PEAKRAARCSEC$$',
  '$$PEAKDEC$$',
  '$$PEAKDECARCSEC$$',
  '$$FOCUSERPOSITION$$',
  '$$FOCUSERTEMP$$',
  '$$APPLICATIONSTARTDATE$$',
  '$$HFR$$',
  '$$SQM$$',
  '$$READOUTMODE$$',
  '$$USBLIMIT$$',
  '$$CAMERA$$',
  '$$TELESCOPE$$',
  '$$ROTATORANGLE$$',
  '$$STARCOUNT$$',
  '$$SEQUENCETITLE$$',
];

export const tokenDisplayNames = {
  $$FILTER$$: 'Filter',
  $$DATE$$: 'Date',
  $$DATEUTC$$: 'Date UTC',
  $$DATEMINUS12$$: 'Session Date',
  $$DATETIME$$: 'Date+Time',
  $$TIME$$: 'Time',
  $$TIMEUTC$$: 'Time UTC',
  $$MJD$$: 'MJD',
  $$FRAMENR$$: 'Frame #',
  $$IMAGETYPE$$: 'Type',
  $$BINNING$$: 'Bin',
  $$SENSORTEMP$$: 'Temp',
  $$TEMPERATURESETPOINT$$: 'Temp Set',
  $$EXPOSURETIME$$: 'Exposure',
  $$TARGETNAME$$: 'Target',
  $$GAIN$$: 'Gain',
  $$OFFSET$$: 'Offset',
  $$RMS$$: 'RMS',
  $$RMSARCSEC$$: 'RMS"',
  $$PEAKRA$$: 'PeakRA',
  $$PEAKRAARCSEC$$: 'PeakRA"',
  $$PEAKDEC$$: 'PeakDec',
  $$PEAKDECARCSEC$$: 'PeakDec"',
  $$FOCUSERPOSITION$$: 'Focuser Pos',
  $$FOCUSERTEMP$$: 'Focuser Temp',
  $$APPLICATIONSTARTDATE$$: 'App Start',
  $$HFR$$: 'HFR',
  $$SQM$$: 'SQM',
  $$READOUTMODE$$: 'Readout',
  $$USBLIMIT$$: 'USB Limit',
  $$CAMERA$$: 'Camera',
  $$TELESCOPE$$: 'Telescope',
  $$ROTATORANGLE$$: 'Rotator',
  $$STARCOUNT$$: 'Stars',
  $$SEQUENCETITLE$$: 'Sequence',
};

export const tokenGroups = [
  {
    label: 'components.settings.imageFile.groups.dateTime',
    tokens: [
      { key: '$$DATE$$', display: 'Date' },
      { key: '$$DATEUTC$$', display: 'Date UTC' },
      { key: '$$DATEMINUS12$$', display: 'Session Date' },
      { key: '$$DATETIME$$', display: 'Date+Time' },
      { key: '$$TIME$$', display: 'Time' },
      { key: '$$TIMEUTC$$', display: 'Time UTC' },
      { key: '$$MJD$$', display: 'MJD' },
    ],
  },
  {
    label: 'components.settings.imageFile.groups.image',
    tokens: [
      { key: '$$IMAGETYPE$$', display: 'Type' },
      { key: '$$FILTER$$', display: 'Filter' },
      { key: '$$FRAMENR$$', display: 'Frame #' },
      { key: '$$EXPOSURETIME$$', display: 'Exposure' },
      { key: '$$BINNING$$', display: 'Bin' },
    ],
  },
  {
    label: 'components.settings.imageFile.groups.camera',
    tokens: [
      { key: '$$SENSORTEMP$$', display: 'Temp' },
      { key: '$$TEMPERATURESETPOINT$$', display: 'Temp Set' },
      { key: '$$GAIN$$', display: 'Gain' },
      { key: '$$OFFSET$$', display: 'Offset' },
      { key: '$$READOUTMODE$$', display: 'Readout' },
      { key: '$$USBLIMIT$$', display: 'USB Limit' },
      { key: '$$CAMERA$$', display: 'Camera' },
    ],
  },
  {
    label: 'components.settings.imageFile.groups.guiding',
    tokens: [
      { key: '$$RMS$$', display: 'RMS' },
      { key: '$$RMSARCSEC$$', display: 'RMS"' },
      { key: '$$PEAKRA$$', display: 'PeakRA' },
      { key: '$$PEAKRAARCSEC$$', display: 'PeakRA"' },
      { key: '$$PEAKDEC$$', display: 'PeakDec' },
      { key: '$$PEAKDECARCSEC$$', display: 'PeakDec"' },
    ],
  },
  {
    label: 'components.settings.imageFile.groups.equipment',
    tokens: [
      { key: '$$FOCUSERPOSITION$$', display: 'Focuser Pos' },
      { key: '$$FOCUSERTEMP$$', display: 'Focuser Temp' },
      { key: '$$TELESCOPE$$', display: 'Telescope' },
      { key: '$$ROTATORANGLE$$', display: 'Rotator' },
    ],
  },
  {
    label: 'components.settings.imageFile.groups.other',
    tokens: [
      { key: '$$TARGETNAME$$', display: 'Target' },
      { key: '$$SEQUENCETITLE$$', display: 'Sequence' },
      { key: '$$APPLICATIONSTARTDATE$$', display: 'App Start' },
      { key: '$$HFR$$', display: 'HFR' },
      { key: '$$SQM$$', display: 'SQM' },
      { key: '$$STARCOUNT$$', display: 'Stars' },
    ],
  },
];

// prettier-ignore
export const exampleValues = {
  '$$FILTER$$': 'Ha',
  '$$DATE$$': '2024-01-15',
  '$$DATEUTC$$': '2024-01-15',
  '$$DATEMINUS12$$': '2024-01-15',
  '$$DATETIME$$': '2024-01-15_21-30-00',
  '$$TIME$$': '21-30-00',
  '$$TIMEUTC$$': '20-30-00',
  '$$MJD$$': '60324',
  '$$FRAMENR$$': '0001',
  '$$IMAGETYPE$$': 'LIGHT',
  '$$BINNING$$': '1x1',
  '$$SENSORTEMP$$': '-10',
  '$$TEMPERATURESETPOINT$$': '-10',
  '$$EXPOSURETIME$$': '300',
  '$$TARGETNAME$$': 'M31',
  '$$GAIN$$': '100',
  '$$OFFSET$$': '10',
  '$$RMS$$': '0.45',
  '$$RMSARCSEC$$': '0.68',
  '$$PEAKRA$$': '0.32',
  '$$PEAKRAARCSEC$$': '0.48',
  '$$PEAKDEC$$': '0.28',
  '$$PEAKDECARCSEC$$': '0.42',
  '$$FOCUSERPOSITION$$': '12500',
  '$$FOCUSERTEMP$$': '5',
  '$$APPLICATIONSTARTDATE$$': '2024-01-15',
  '$$HFR$$': '2.1',
  '$$SQM$$': '20.5',
  '$$READOUTMODE$$': '0',
  '$$USBLIMIT$$': '40',
  '$$CAMERA$$': 'ZWO ASI294MC Pro',
  '$$TELESCOPE$$': 'RC8',
  '$$ROTATORANGLE$$': '45',
  '$$STARCOUNT$$': '142',
  '$$SEQUENCETITLE$$': 'M31_Session',
};
