import fs from "fs";

function getNestedValue(obj, path) {
  return path.split(".").reduce((current, prop) => current?.[prop], obj);
}

function setNestedValue(obj, path, value) {
  const parts = path.split(".");
  let current = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    if (!current[parts[i]]) current[parts[i]] = {};
    current = current[parts[i]];
  }
  current[parts[parts.length - 1]] = value;
}

const keys = [
  "components.rotator.settings.Backlash",
  "components.flat.settings.title",
  "components.flat.settings.heater",
  "components.flat.settings.openPosition",
  "components.flat.settings.closedPosition",
  "components.flat.settings.currentPosition",
  "components.flat.settings.noSettingsForDevice",
  "plugins.hocusfocus.title",
  "plugins.hocusfocus.tabs.aberration",
  "plugins.hocusfocus.tabs.aberrationOptions",
  "plugins.hocusfocus.tabs.autoFocusOptions",
  "plugins.hocusfocus.tabs.starDetection",
  "plugins.hocusfocus.modal.selectDirectory",
  "plugins.hocusfocus.modal.loading",
  "plugins.hocusfocus.modal.placeholder",
  "plugins.hocusfocus.modal.proceed",
  "plugins.hocusfocus.modal.cancel",
  "plugins.hocusfocus.aberrationInspector.title",
  "plugins.hocusfocus.aberrationInspector.runButton",
  "plugins.hocusfocus.aberrationInspector.cancelButton",
  "plugins.hocusfocus.aberrationInspector.loadSaved",
  "plugins.hocusfocus.aberrationInspector.clearAnalyses",
  "plugins.hocusfocus.aberrationInspector.focusCurveAnalysis",
  "plugins.hocusfocus.aberrationInspector.finalFocusDataSummary",
  "plugins.hocusfocus.aberrationInspector.backfocusError",
  "plugins.hocusfocus.aberrationInspector.hfrDifference",
  "plugins.hocusfocus.aberrationInspector.innerHFR",
  "plugins.hocusfocus.aberrationInspector.outerHFR",
  "plugins.hocusfocus.aberrationInspector.moveSensor",
  "plugins.hocusfocus.aberrationInspector.flattener",
  "plugins.hocusfocus.aberrationInspector.tiltCornerMeasurements",
  "plugins.hocusfocus.aberrationInspector.sensorSide",
  "plugins.hocusfocus.aberrationInspector.focuserPosition",
  "plugins.hocusfocus.aberrationInspector.adjustmentSteps",
  "plugins.hocusfocus.aberrationInspector.adjustmentMicrons",
  "plugins.hocusfocus.aberrationInspector.rSquared",
  "plugins.hocusfocus.aberrationInspector.unitMicrons",
  "plugins.hocusfocus.aberrationInspector.unitSteps",
  "plugins.hocusfocus.aberrationInspectorOptions.loading",
  "plugins.hocusfocus.aberrationInspectorOptions.noOptions",
  "plugins.hocusfocus.aberrationInspectorOptions.error",
  "plugins.hocusfocus.aberrationInspectorOptions.inspectorSettings",
  "plugins.hocusfocus.aberrationInspectorOptions.micronsPerFocuserStep",
  "plugins.hocusfocus.aberrationInspectorOptions.retry",
  "plugins.hocusfocus.aberrationInspectorOptions.resetToDefaults",
  "plugins.hocusfocus.aberrationInspectorOptions.resetting",
  "plugins.hocusfocus.autoFocusOptions.loading",
  "plugins.hocusfocus.autoFocusOptions.error",
  "plugins.hocusfocus.autoFocusOptions.retry",
  "plugins.hocusfocus.autoFocusOptions.basicSettings",
  "plugins.hocusfocus.autoFocusOptions.hfrValidation",
  "plugins.hocusfocus.directoryBrowser.browse",
  "plugins.hocusfocus.directoryBrowser.error",
  "plugins.hocusfocus.starDetection.loading",
  "plugins.hocusfocus.starDetection.error",
  "plugins.hocusfocus.starDetection.retry",
  "plugins.hocusfocus.starDetection.generalSettings",
  "plugins.hocusfocus.starDetection.advancedMode",
  "plugins.hocusfocus.starDetection.useHotpixelThresholding",
  "plugins.hocusfocus.starDetection.useAutoFocusCrop",
  "plugins.hocusfocus.starDetection.fitPSF",
  "plugins.hocusfocus.starDetection.hotpixelFiltering",
  "plugins.hocusfocus.starDetection.noiseReducedStarMeasurement",
  "plugins.hocusfocus.starDetection.debugMode",
  "plugins.hocusfocus.starDetection.simpleModeSettings",
  "plugins.hocusfocus.starDetection.noiseLevel",
  "plugins.hocusfocus.common.error",
  "plugins.hocusfocus.common.loading",
  "pinsDevices.title",
  "pinsDevices.powerBox",
  "pinsDevices.meteoStation",
  "pinsDevices.configurationTab",
  "pinsDevices.generalTab",
  "pinsDevices.wifiTab",
  "pinsDevices.powerPortsTab",
  "pinsDevices.dewPortsTab",
  "pinsDevices.adjustablePowerTab",
  "pinsDevices.weatherTab",
  "pinsDevices.usbPortsTab",
  "pinsDevices.settings.title",
  "pinsDevices.settings.temperature",
  "pinsDevices.settings.humidity",
  "pinsDevices.settings.dewPoint",
  "pinsDevices.settings.placeholders.networkName",
  "pinsDevices.settings.placeholders.password",
  "pinsDevices.settings.placeholders.passwordHint",
  "pinsDevices.settings.validation.passwordRequired",
  "pinsDevices.ports.disableOnStartup",
  "pinsDevices.ports.enableOnStartup",
  "pinsDevices.ports.alwaysEnabled",
  "pinsDevices.ports.status",
  "pinsDevices.ports.current",
  "pinsDevices.ports.currentVoltage",
  "pinsDevices.ports.currentPower",
  "pinsDevices.ports.outputVoltage",
  "pinsDevices.ports.powerLevel",
  "pinsDevices.ports.defaultVoltage",
  "pinsDevices.dew.status",
  "pinsDevices.dew.autoMode",
  "pinsDevices.dew.disableAutoMode",
  "pinsDevices.dew.enableAutoMode",
  "pinsDevices.dew.probeTemperature",
  "pinsDevices.dew.current",
  "pinsDevices.dew.maxCurrent",
  "pinsDevices.dew.currentPower",
  "pinsDevices.dew.autoThreshold",
  "pinsDevices.dew.autoThresholdDisplay",
  "pinsDevices.dew.autoThresholdDescription",
  "pinsDevices.dew.powerLevel",
  "pinsDevices.power.buckConverter",
  "pinsDevices.power.pwmOutput",
  "pinsDevices.general.rail12v",
  "pinsDevices.general.rail5v",
  "pinsDevices.general.averageAmps",
  "pinsDevices.general.ampsPerHour",
  "pinsDevices.general.wattsPerHour",
  "pinsDevices.weather.luxUnit",
  "pinsDevices.errors.failedRenamePort",
  "pinsDevices.errors.failedTogglePort",
  "pinsDevices.errors.failedToggleBootState",
  "pinsDevices.errors.failedToggleAutoMode",
  "pinsDevices.errors.failedSetPowerLevel"
];

const en = JSON.parse(fs.readFileSync("src/locales/en.json", "utf-8"));

console.log("English values:\n");
keys.forEach(key => {
  const value = getNestedValue(en, key);
  console.log(`${key}: ${value}`);
});
